services:
    laravel.test:
        command:
            - /bin/sh
            - '-c'
            - 'composer install && npm i && php artisan serve --host=192.168.101.10 --port=${LARAVEL_PORT} & npm run dev'
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${LARAVEL_PORT}:${LARAVEL_PORT}'
            - '${VITE_PORT}:${VITE_PORT}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            sail:
                ipv4_address: 192.168.101.10
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_TCP_PORT: '${DB_PORT}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            sail:
                ipv4_address: 192.168.101.11
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    adminer:
        image: adminer
        restart: always
        ports:
            - '${ADMINER_PORT}:${ADMINER_PORT}'
        networks:
            sail:
                ipv4_address: 192.168.101.12
networks:
    sail:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 192.168.101.0/24
volumes:
    sail-mysql:
        driver: local
