// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('TC008', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('TC008', async function() {
    await driver.findElement(By.css(".hover\\3A bg-blue-600")).click()
    await driver.findElement(By.css(".px-3")).click()
    await driver.findElement(By.css(".px-3")).sendKeys("Test table")
    await driver.findElement(By.css(".px-4:nth-child(2)")).click()
{
  const elements = await driver.findElements(By.css(".flex:nth-child(3) > .roboto-font-bold"))
  assert(elements.length)
}
  })
})
