// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('TC-010', function() {
    this.timeout(30000)
    let driver
    let vars

    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('TC-010', async function() {
        await driver.get("https://dev.tudera.com/")
        await driver.findElement(By.id("email")).click()
        await driver.findElement(By.id("email")).sendKeys("test@test.com")
        await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
        await driver.wait(until.elementLocated(By.id("password")), 10000)
        await driver.findElement(By.id("password")).click()
        await driver.findElement(By.id("password")).sendKeys("password")
        await driver.executeScript("arguments[0].click();", await driver.findElement(By.css("button[type='submit']")));
        await driver.wait(until.elementLocated(By.css(".me-2")), 10000)
        const todoBtn = driver.findElement(By.xpath("//*[text()='Add new todo']"));
        await driver.wait(until.elementIsVisible(todoBtn), 10000);
        await driver.executeScript("arguments[0].click();", todoBtn);
        await driver.wait(until.elementLocated(By.css(".flex > .px-3")), 10000)
        await driver.findElement(By.css(".flex > .px-3")).sendKeys("Test Todo")
        await driver.findElement(By.css(".hover\\3A bg-blue-700")).click()
        await driver.findElement(By.css(".me-2")).click()
        await driver.findElement(By.css(".bg-transparent:nth-child(2)")).click()
    })
})
