// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('TC-001', function() {
    this.timeout(30000)
    let driver
    let vars

    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('TC-001', async function() {
        await driver.get("https://dev.tudera.com/")
        await driver.wait(until.elementLocated(By.css(".peer-checked\\/signup\\3Atext-gray-900")), 3000)
        await driver.findElement(By.css(".peer-checked\\/signup\\3Atext-gray-900")).click()
        await driver.findElement(By.css(".left-3")).click()
        let uuid = await driver.executeScript("return window.crypto.randomUUID()")
        await driver.findElement(By.id("email")).sendKeys(uuid+"@gmail.com")
        await driver.findElement(By.css(".bg-blue-600")).click()
        await driver.wait(until.elementLocated(By.css(".max-w-screen")), 3000)
        await driver.findElement(By.css(".flex > span")).click()
        const fileInput = await driver.findElement(By.css("input[type='file']"))
        await fileInput.sendKeys("/Users/preilakos/proj/mv-tudera/public/assets/user.png")
        await driver.findElement(By.id("first-name")).click()
        await driver.findElement(By.id("first-name")).sendKeys("dummy")
        await driver.findElement(By.id("last-name")).sendKeys("data")
        await driver.findElement(By.id("tel")).sendKeys("+36000000000")
        await driver.findElement(By.id("password")).sendKeys("password")
        await driver.executeScript("arguments[0].click();", await driver.findElement(By.css("button[type='submit']")));
        await driver.wait(until.elementLocated(By.css(".text-2xl")), 3000)
        await driver.sleep(10000)
        const workspaceText = await driver.findElement(By.css(".text-2xl")).getText()
        assert.strictEqual(workspaceText, "Create your workspace")
    })
})
