// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('TC-005', function() {
    this.timeout(30000)
    let driver
    let vars

    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('TC-005', async function() {
        await driver.get("https://dev.tudera.com/")
        await driver.findElement(By.id("email")).click()
        await driver.findElement(By.id("email")).sendKeys("test@test.com")
        await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
        await driver.wait(until.elementLocated(By.id("password")), 10000)
        await driver.findElement(By.id("password")).click()
        await driver.findElement(By.id("password")).sendKeys("password")
        await driver.executeScript("arguments[0].click();", await driver.findElement(By.css("button[type='submit']")));
        await driver.wait(until.elementLocated(By.css(".me-2")), 10000)
        await driver.get("https://dev.tudera.com/workspaces/join");
        await driver.wait(until.elementLocated(By.css("input[placeholder='Invite code']")), 10000)
        const input = await driver.findElement(By.css("input[placeholder='Invite code']"));
        await input.sendKeys("073c46d4-444f-4d1a-873c-05733ebefe3a");
        await driver.executeScript("arguments[0].click();", await driver.findElement(By.xpath("//*[text()='Connect']")));
        await driver.wait(until.elementLocated(By.css(".mosha__toast")), 10000)
    })
})
