// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC006', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC006', async function() {
    await driver.get("https://dev.tudera.com/auth")
    await driver.manage().window().setRect({ width: 709, height: 860 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("abrahamdavidjanos@gmail.com")
    await driver.findElement(By.css(".bg-blue-600")).click()
    {
      const element = await driver.findElement(By.css(".bg-blue-600"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.css(".bg-blue-600")).click()
    {
      const element = await driver.findElement(By.css(".bg-blue-600"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const elements = await driver.findElements(By.css(".roboto-font-small"))
      assert(elements.length)
    }
  })
})
