// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC003', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC003', async function() {
    await driver.get("https://dev.tudera.com/auth")
    await driver.manage().window().setRect({ width: 709, height: 835 })
    await driver.findElement(By.css(".left-3")).click()
    await driver.findElement(By.id("email")).sendKeys("gcziati@gmail.com")
    await driver.findElement(By.css(".bg-blue-600")).click()
    {
      const elements = await driver.findElements(By.css(".block"))
      assert(elements.length)
    }
  })
})
