// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC009', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC009', async function() {
    await driver.get("https://dev.tudera.com/dashboard")
    await driver.manage().window().setRect({ width: 709, height: 860 })
    await driver.findElement(By.css(".md\\3A flex-col")).click()
    await driver.findElement(By.css(".cursor-pointer:nth-child(2) > .cursor-pointer")).click()
    await driver.findElement(By.css(".bg-\\[\\#5D5E5B\\]")).click()
    {
      const dropdown = await driver.findElement(By.css(".bg-\\[\\#5D5E5B\\]"))
      await dropdown.findElement(By.xpath("//option[. = 'Status']")).click()
    }
    await driver.findElement(By.css(".text-xl")).click()
  })
})
